webpack/main/routes.py
from flask import render_template, request, Blueprint, url_for, redirect
from webpack.models import Post, Comment, Post_like, Chat, User
from datetime import datetime
from flask_login import current_user

main = Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
    if not (current_user.is_authenticated):
        return redirect(url_for('users.login'))
    todays_datetime = datetime(datetime.today().year, datetime.today().month, datetime.today().day)
    all_his_comments = Comment.query.order_by(Comment.timestamp.desc()).filter(Comment.commentor == current_user.username,Comment.timestamp >= todays_datetime).all()
    all_got_comments = Comment.query.order_by(Comment.timestamp.desc()).filter_by(post_writer = current_user.username).all()
    all_likes = Post_like.query.order_by(Post_like.timestamp.desc()).filter_by(user_post = current_user.id).all()
    all_chats = Chat.query.order_by(Chat.time_of_chat.desc()).filter_by(user__id = current_user.id).all()
    page_no = request.args.get('page',1,type = int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page = page_no,per_page = 4)
    all_like_users = []
    all_chat_users = []
    all_his_comment_users = []
    for like in all_likes:
        user = User.query.get_or_404(like.user__id)
        all_like_users.append([user.username,user.id,like.post__id])
    for chat in all_chats:
        user = User.query.get_or_404(chat.user_start_id)
        all_chat_users.append([user.username,user.id])
    for comment in all_his_comments:
        post = Post.query.get_or_404(comment.post__id)
        all_his_comment_users.append([post.author,comment.post__id])
    if current_user.is_authenticated:
        
        profile_image = url_for('static',filename = 'images/' + current_user.profile_pic)
        
        if current_user.theme == 'NULL':
            return render_template('Home_page_light.html' , title = "Home Page",all_got_comments=all_got_comments, all_his_comments = all_his_comment_users, all_likes = all_like_users, all_chats = all_chat_users ,posts = posts, profile_pic = profile_image , username_menu = current_user.username,present_time = datetime.utcnow())
        else:
            return render_template('Home_page_dark.html' , title = "Home Page" ,all_got_comments=all_got_comments, all_his_comments = all_his_comment_users, all_likes = all_like_users, all_chats = all_chat_users,posts = posts, profile_pic = profile_image , username_menu = current_user.username,present_time = datetime.utcnow())
    else:
        profile_image = url_for('static',filename = 'images/' + 'default_profile_pic.jpg')
        return render_template('Home_page_dark.html' , title = "Home Page",posts = posts,all_got_comments=all_got_comments, all_his_comments = all_his_comment_users, all_likes = all_like_users, all_chats = all_chat_users, profile_pic = profile_image , username_menu = 'Unknown User',present_time = datetime.utcnow() )

webpack/posts/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, abort, flash
from flask_login import current_user, login_required
from webpack import db
from webpack.models import Post,Comment,User,Post_like
from webpack.posts.forms import Post_form, Comment_form
from datetime import datetime
from webpack.users.utils import send_post_delete_email

posts = Blueprint('posts',__name__)

@login_required
@posts.route("/ask/new", methods = ['GET','POST'])
def create_post():
    form = Post_form()
    if form.validate_on_submit():
        post = Post(title = form.post_title.data, content = form.content.data, author = current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your Question is Uploded! ', 'success')
        return redirect(url_for('main.home'))
    if current_user.theme == 'NULL':
        return render_template('create_post.html', title = "Ask", form = form, form_title_webpage = "Ask Here" , button_name = "Ask")
    else:
        return render_template('create_post_dark.html', title = "Ask", form = form, form_title_webpage = "Ask Here" , button_name = "Ask")

@login_required
@posts.route("/like/<int:post_id>", methods = ['POST','GET'])
def like(post_id):
    post = Post.query.get_or_404(post_id)
    user_exist = Post_like.query.filter_by(post__id = post_id,user__id = current_user.id).first()
    if post and (not user_exist):
        like = Post_like(post__id = post_id, user_post = post.author.id, user__id = current_user.id)
        db.session.add(like)
        db.session.commit()
    elif post and user_exist:
        db.session.delete(user_exist)
        db.session.commit()

    return redirect(url_for('posts.post', post_id = post_id))

@login_required
@posts.route("/ask/<int:post_id>", methods = ['POST','GET'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    user_exist = Post_like.query.filter_by(post__id = post_id,user__id = current_user.id).first()
    no_of_likes = len(Post_like.query.filter_by(post__id = post_id).all())
    post_like_name = "like"
    print(post.author.is_authenticated)
    if post and (not user_exist):
        post_like_name = "like"
    elif post and user_exist:
        post_like_name = "unlike"
    
    form = Comment_form()
    _comments = Comment.query.order_by(Comment.timestamp.desc()).filter_by(post__id = post_id).all()
    if current_user.is_authenticated:
        form.commentor.data = current_user.username
    if form.validate_on_submit and request.method == 'POST':
        # flash('Not ommented successfully!!!', 'success')
        if current_user.username == form.commentor.data:
            comment = Comment(commentor = form.commentor.data,comment = form.comment.data, post_writer = post.author.username, post__id = post_id, profile_pic = current_user.profile_pic)
            db.session.add(comment)
            db.session.commit()
            flash('Commented successfully!!!', 'success')
            return redirect(url_for('main.home'))
        elif current_user.username != form.commentor.data:
            flash(f'Please don\'t use anyone else\'s username','danger')
            return  redirect(url_for('main.home'))
        else:
            flash(f'Your Comment is not uploaded successfully!','danger')
    if current_user.is_authenticated:
        
        profile_image = url_for('static',filename = 'images/' + current_user.profile_pic)

        if current_user.theme == 'NULL':
            return render_template('sep_post_light.html' , title = post.title ,post = post, profile_pic = profile_image ,_comments = _comments ,no_of_likes = no_of_likes ,username_menu = current_user.username,form = form,post_like_name = post_like_name ,present_time = datetime.utcnow())
        else:
            return render_template('sep_post_dark.html' , title = post.title ,post = post, profile_pic = profile_image ,_comments = _comments ,no_of_likes = no_of_likes ,username_menu = current_user.username,form = form,post_like_name = post_like_name ,present_time = datetime.utcnow())
    else:
        profile_image = url_for('static',filename = 'images/' + 'default_profile_pic.jpg')

        return render_template('sep_post_light.html' , title = post.title ,post = post, profile_pic = profile_image ,_comments = _comments ,no_of_likes = no_of_likes , username_menu = 'Unknown User' , form = form,post_like_name = post_like_name , present_time = datetime.utcnow())

# @login_required
# @posts.route("/post_id=<int:post_id>/viewcomments", methods = ['POST','GET'])
# def view_comments(post_id):
#     form = Comment_form()
#     post_id = request.args.get('post_id',1,type = int)
#     page_no = request.args.get('page',1,type = int)
#     _comments = Comment.query.order_by(Comment.timestamp.desc()).filter_by(post__id = post_id).paginate(page = page_no, per_page = 5)
#     user = current_user
#     if current_user.is_authenticated:
#         form.commentor.data = current_user.username
#     if form.validate_on_submit and request.method == 'POST':
#         # flash('Not ommented successfully!!!', 'success')
#         if current_user.username == form.commentor.data:
#             comment = Comment(commentor = form.commentor.data,comment = form.comment.data, post__id = post_id)
#             db.session.add(comment)
#             db.session.commit()
#             flash('Commented successfully!!!', 'success')
#             return redirect(url_for('main.home'))
#         elif current_user.username != form.commentor.data:
#             flash(f'Please don\'t use anyone else\'s username','danger')
#             return  redirect(url_for('main.home'))
#         else:
#             flash(f'Your Comment is not uploaded successfully!','danger')
#     if current_user.is_authenticated:
#         return render_template('comment_page.html', title = "Comments",form = form ,user = user, _comments = _comments, present_time = datetime.utcnow(),username_menu = user.username)
#     else:
#         return redirect(url_for('users.login'))
    
@login_required
@posts.route("/ask/<int:post_id>/update" , methods = ['POST','GET'])
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = Post_form()
    if form.validate_on_submit():
        post.title = form.post_title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your question is updated!','success')
        return redirect(url_for('posts.post', post_id = post.id))
    form.post_title.data = post.title
    form.content.data = post.content
    if current_user.theme == 'NULL':
        return render_template('create_post.html', title = "Update Question", form = form , form_title_webpage = "Edit Question" , button_name = 'Update')
    else:
        return render_template('create_post_dark.html', title = "Update Question", form = form , form_title_webpage = "Edit Question" , button_name = 'Update')

@login_required
@posts.route("/ask/<int:post_id>/delete" , methods = ['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    post_comments = Comment.query.filter_by(post__id = post_id).all()
    if current_user.username != "ADMIN01":
        if post.author != current_user:
            abort(403)
    for comment in post_comments:
        db.session.delete(comment)
    if current_user.username == "ADMIN01":
        send_post_delete_email(post.author,post)
    db.session.delete(post)
    db.session.commit()
    flash('Your question is deleted successfully!','success')
    return redirect(url_for('main.home'))

webpack/templates/create_post_dark.html
{% extends "layout.html" %}
{% block files %}
    <link rel="stylesheet" href="{{ url_for('static',filename='dark_theme.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'MDB/css/mdb.css') }}">
{% endblock files %}
{% block content %}
<div id="loader" class="center"></div> 
    <div class = "__container">
      {% with messages = get_flashed_messages(with_categories = true) %}
            {% if messages %}
                {% for category,message in messages%}
                    <div>
                        {% if category == "info" %}
                            <div class = "alert alert-info" ><i class="fas fa-bell fl-fw icon_bell"></i>&nbsp;&nbsp;&nbsp;&nbsp;{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button></div>
                        {% elif category == "success" %}
                            <div class = "alert alert-success" ><i class="fas fa-check-circle fl-fw icon_tick"></i>&nbsp;&nbsp;&nbsp;&nbsp;{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button></div>
                        {% elif category == "danger" %}
                            <div class = "alert alert-danger" ><i class="fas fa-times-circle fl-fw icon_danger"></i>&nbsp;&nbsp;&nbsp;&nbsp;{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button></div>
                        {% endif %}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <!--Navbar -->
        <nav class="mb-1 navbar navbar-expand-lg navbar-dark" style="background: #131419;">
            <span class="my-brand" style="color: #fff; font-size: 20px; font-weight: 600; cursor: pointer; margin-right: 20px;">AskNSolve</span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
            aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
            <ul class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                
                <li class="nav-item menu-option">
                    <a class="nav-link button-i" style="color: grey; font-size: 15px; font-weight: 600;" onmouseover="this.style.color = 'lime'" onmouseout="this.style.color = 'grey'" href="{{url_for('main.home')}}">Home</a>
                </li>
                <li class="nav-item menu-option">
                <a class="nav-link button-ii active-ii" style="color: orange; font-size: 15px; font-weight: 600;" onmouseover="this.style.color = '#fff'" onmouseout="this.style.color = 'orange'" href="{{url_for('posts.create_post')}}">Ask</a>
                </li>
                <li class="nav-item menu-option">
                <a class="nav-link button-iii" style="color: grey; font-size: 15px; font-weight: 600;" onmouseover="this.style.color = '#fff'" onmouseout="this.style.color = 'grey'" href="{{url_for('users.account',user_id = current_user.id)}}">Account</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto nav-flex-icons">
                {% if current_user.is_authenticated %}
                <li class="nav-item menu-option">
                    <a class="nav-link button-iv" style="color: rgb(126, 0, 0); font-size: 15px; font-weight: 600;" onmouseover="this.style.color = '#FF0000'" onmouseout="this.style.color = 'crimson'" a href="{{url_for('users.logout')}}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item menu-option">
                    <a class="nav-link button-ii" style="color:grey; font-size: 15px; font-weight: 600;" onmouseover="this.style.color = 'orange'" onmouseout="this.style.color = 'grey'" href="{{url_for('users.login')}}" >Login</a>
                </li>
                <li class="nav-item menu-option">
                    <a class="nav-link button-i" style="color: grey; font-size: 15px; font-weight: 600;" onmouseover="this.style.color = 'lime'" onmouseout="this.style.color = 'grey'" href="{{url_for('users.register')}}" >Register</a>
                </li>
                {% endif %}
            </ul>
            </div>
        </nav>
      <!--/.Navbar -->
      <div class="_container" style="margin-top: 50px;">
        <div class="input-1">
          <div class="form-3" style="padding: 20px; margin-top: -100px; border-radius: 5px;">
            <form action="" method = "POST">
              {{ form.hidden_tag() }}
              <fieldset class="post_form">
                <h2 style="color: rgb(0, 255, 229); text-align: center;text-shadow: 0px 0px 5px rgba(0, 255, 229,0.7),0px 0px 10px rgba(0, 255, 229,0.7);">{{ form_title_webpage }}</h2>
                <div class="post_title" style="margin: 10px; margin-top: 30px;">
                  {{ form.post_title(class = "form-control-2", style = "margin:0;",placeholder = "Title should be clear and specific ") }}
                  {% if form.post_title.errors %}
                    {%for error in form.post_title.errors%}
                      <small class="form-text text-danger" style="margin-left: 10px;">{{ error }}</small>
                    {%endfor%}
                  {% endif %}
                </div>
                <div class="post_content" style="margin: 10px; margin-top: 30px;">
                  {{ form.content(class="form-control-2",style = "margin:0;", id="exampleFormControlTextarea4", rows="3", placeholder = "Explain your doubt ") }}
                  {% if form.content.errors %}
                    {%for error in form.content.errors%}
                      <small class="form-text text-danger" style="margin-left: 10px;">{{ error }}</small>
                    {%endfor%}
                  {% endif %}
                </div>
                <div class="text-center">
                  {{ form.submit(class = "ask_button") }}
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
    </div>
    <script type="text/javascript" src="{{ url_for('static',filename='MDB/js/jquery.min.js')}}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{{ url_for('static',filename='MDB/js/popper.min.js')}}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{{ url_for('static',filename='MDB/js/bootstrap.min.js')}}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{{ url_for('static',filename='MDB/js/mdb.min.js')}}"></script>
    <!-- Your custom scripts (optional) -->
{% endblock content %}

webpack/templates/only_his_post.html
{% extends "layout.html" %}
{% block files %}
    <link rel="stylesheet" href="{{ url_for('static',filename='light_theme.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='my_style.css')}}">
    
    <link rel="stylesheet" href="{{ url_for('static',filename = 'MDB/css/mdb.css') }}">

{% endblock files %}
{% block content %}
<div id="loader" class="center"></div> 
    <div class="__container">
            
            {% with messages = get_flashed_messages(with_categories = true) %}
                {% if messages %}
                    {% for category,message in messages%}
                        <div>
                            {% if category == "info" %}
                                <div class = "alert alert-info" ><i class="fas fa-bell fl-fw icon_bell"></i>&nbsp;&nbsp;&nbsp;&nbsp;{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button></div>
                            {% elif category == "success" %}
                                <div class = "alert alert-success" ><i class="fas fa-check-circle fl-fw icon_tick"></i>&nbsp;&nbsp;&nbsp;&nbsp;{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button></div>
                            {% elif category == "danger" %}
                                <div class = "alert alert-danger" ><i class="fas fa-times-circle fl-fw icon_danger"></i>&nbsp;&nbsp;&nbsp;&nbsp;{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button></div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            

            

            

            
            <!--Navbar -->
            <nav class="mb-1 navbar navbar-expand-lg navbar-dark">
                <a class="navbar-brand" href="#" style="color: rgb(43, 148, 137); font-size: 20px; font-weight: 600;"><span class="letter-1">A</span>skNSolve</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
                aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
                <ul class="navbar-nav mr-auto">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item menu-option active-1111">
                    <a class="nav-link" style="color: rgb(51, 177, 164); font-size: 15px; font-weight: 600;" onmouseover="this.style.color = 'grey'" onmouseout="this.style.color = 'rgb(51, 177, 164)'" href="{{url_for('main.home')}}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                    </li>
                    <li class="nav-item menu-option">
                    <a class="nav-link" style="color: rgb(51, 177, 164); font-size: 15px; font-weight: 600;" onmouseover="this.style.color = 'grey'" onmouseout="this.style.color = 'rgb(51, 177, 164)'" href="{{url_for('posts.create_post')}}">Ask</a>
                    </li>
                    <li class="nav-item menu-option">
                    <a class="nav-link" style="color: rgb(51, 177, 164); font-size: 15px; font-weight: 600;" onmouseover="this.style.color = 'grey'" onmouseout="this.style.color = 'rgb(51, 177, 164)'" href="{{url_for('users.account',user_id = current_user.id)}}">Account</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ml-auto nav-flex-icons">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item menu-option">
                        <a class="nav-link" style="color: crimson; font-size: 15px; font-weight: 600;" onmouseover="this.style.color = 'grey'" onmouseout="this.style.color = 'crimson'" a href="{{url_for('users.logout')}}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item menu-option">
                        <a class="nav-link" style="color: crimson; font-size: 15px; font-weight: 600;" onmouseover="this.style.color = 'grey'" onmouseout="this.style.color = 'crimson'" href="{{url_for('users.login')}}" >Login</a>
                    </li>
                    <li class="nav-item menu-option">
                        <a class="nav-link" style="color: crimson; font-size: 15px; font-weight: 600;" onmouseover="this.style.color = 'grey'" onmouseout="this.style.color = 'crimson'" href="{{url_for('users.register')}}" >Register</a>
                    </li>
                    {% endif %}
                </ul>
                </div>
            </nav>
            <!--/.Navbar -->
  




            
            <div class="_container" >
                
                <div class="input-1">
                    {% for post in posts.items %}
                            <div class="form-1">
                                <div class="card" style="background: transparent; box-shadow: 0 0 0 0; width: 100%; border-radius: 10px;">
                                    <div class="card-header">
                                        {% if current_user.is_authenticated %}
                                            <a href="{{ url_for('users.account',user_id = post.author.id) }}"><img src="{{ url_for('static',filename = 'images/'+post.author.profile_pic)}}" class="profile-pic-1" alt="Profile Picture">
                                        {% else %}
                                            <a href="{{ url_for('users.login',user_id = post.author.id) }}"><img src="{{ url_for('static',filename = 'images/'+post.author.profile_pic)}}" class="profile-pic-1" alt="Profile Picture">
                                        {% endif %}
                                            </a>
                                        <div style="width: 40%; padding-left: 2px; height: 28px; margin-left: 65px; margin-top: -45px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">
                                        {% if current_user.is_authenticated %}
                                            <a href="{{ url_for('users.account',user_id = post.author.id) }}" style="font-size: 16px; margin-left: -1px; font-weight: 510; color: dimgray;">
                                        {% else %}
                                            <a href="{{ url_for('users.login') }}" style="font-size: 16px; margin-left: -1px; font-weight: 510; color: dimgray;">
                                        {% endif %}
                                            {{ post.author.username }}</a></div>
                                        
                                        <div class="text-right" style="width: 25%; padding-left: 2px; float: right; font-size: 10px; margin-top: -23px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{ post.date_posted.strftime('%H:%M:%S') }} &nbsp;&nbsp;&nbsp;{{ post.date_posted.strftime('%d/%m/%Y') }}</div>
                                    </div>
                                    <div class="card-body">
                                        {% if current_user.is_authenticated %}
                                                    <a href="{{url_for('posts.post', post_id = post.id)}}" ><p class="post_title" style="color: rgb(43, 148, 137); font-size: 15px; font-weight: 600;display: block; width: 90%; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;" onmouseover="this.style.color = 'grey'" onmouseout="this.style.color = 'rgb(43, 148, 137)'">
                                                {% else %}
                                                    <a href="{{url_for('users.login')}}" ><p class="post_title" style="color: rgb(43, 148, 137); font-size: 15px; font-weight: 600; display: block; width: 90%; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;" onmouseover="this.style.color = 'grey'" onmouseout="this.style.color = 'rgb(43, 148, 137)'">
                                                {% endif %}
                                                        
                                                    {{ post.title }}
                                                    </p></a>
                                    

                                    
                                    </div>
                                </div>
                            </div>
                                
                        {% endfor %}
                        <div class="text-center">
                            <div class="btn-group">
                                {% for no in posts.iter_pages(left_edge = 1,right_edge = 1, left_current = 1, right_current = 2) %}
                                    {% if no %}
                                        {% if posts.page == no %}
                                            <a href="{{ url_for('main.home',page = no) }}" class="page-i">{{ no }}</a>
                                        {% else %}
                                            <a href="{{ url_for('main.home',page = no) }}" class="page-i">{{ no }}</a>
                                        {% endif %}
                                    {% else %}
                                        <a href="#" class="page-i">...</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                </div>
            </div>
    </div>








        







    
    
    
  <!-- jQuery -->
  <script type="text/javascript" src="{{ url_for('static',filename='MDB/js/jquery.min.js')}}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{{ url_for('static',filename='MDB/js/popper.min.js')}}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{{ url_for('static',filename='MDB/js/bootstrap.min.js')}}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{{ url_for('static',filename='MDB/js/mdb.min.js')}}"></script>
  <!-- Your custom scripts (optional) -->
  <script>
          $(function() {

      $(".get-nicer").niceScroll("div.nice-wrapper", {
        cursorwidth: "12px"
      });

      $(".get-nicer").scroll(function() {
        $("#scroll-info-value").val($(".get-nicer").scrollTop());
      });

      $("a.btn").click(function(e) {
        e.preventDefault();

        console.log('click', e.target);

        $('#nice-modal1').modal();
      });

    });

  </script>
{% endblock content %}